name: yawcalc
main: com.flyingsaturn.yawcalc.YawCalculator
version: 0.0.1
api-version: 1.15
description: Calculates the yaw value when two coordinates are given
commands:
  calcyaw:
    description: Calculates the yaw angle between two coordinates.
    usage: /calcyaw <CurrentX> <CurrentZ> <DestX> <DestZ>